services:
  downloader:
    build: downloader
    volumes:
      - type: bind
        source: ./data
        target: /data
    init: true

  viewer:
    build: viewer
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./data
        target: /data
    init: true
