root: true
env:
  browser: true
  es2021: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - "@nuxtjs/eslint-config-typescript"
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:nuxt/recommended
rules:
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  func-call-spacing:
    - error
    - never
  "@typescript-eslint/ban-ts-comment": off
