# 任意のレジストリに Docker image を公開orビルドする。
# プルリクの作成・更新時に動作する。

name: Docker

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/docker.yml
  pull_request_target:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.merged == true && 'master' || github.event.pull_request.head.sha }}

jobs:
  docker-ci:
    name: Docker CI
    uses: book000/templates/.github/workflows/reusable-docker.yml@master
    with:
      targets: >-
        [
          { imageName: "tomacheese/fetch-youtube-bgm-downloader", context: "downloader", file: "downloader/Dockerfile", packageName: "fetch-youtube-bgm-downloader" },
          { imageName: "tomacheese/fetch-youtube-bgm-viewer", context: "viewer", file: "viewer/Dockerfile", packageName: "fetch-youtube-bgm-viewer" }
        ]
      platforms: linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
